stages:
  - build
  - test
  - package
  - docker

variables:
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"
  MAVEN_CLI_OPTS: "--batch-mode --errors --fail-at-end --show-version"

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - .m2/repository

before_script:
  - export PATH=$PATH:$CI_PROJECT_DIR/mvnw

build:
  stage: build
  image: maven:3.9.6-eclipse-temurin-21
  script:
    - ./mvnw $MAVEN_CLI_OPTS clean compile
  only:
    - merge_requests
    - master

test:
  stage: test
  image: maven:3.9.6-eclipse-temurin-21
  script:
    - ./mvnw $MAVEN_CLI_OPTS test
  artifacts:
    reports:
      junit: target/surefire-reports/*.xml

package:
  stage: package
  image: maven:3.9.6-eclipse-temurin-21
  script:
    - ./mvnw $MAVEN_CLI_OPTS clean package -DskipTests
  artifacts:
    paths:
      - target/*.jar
    expire_in: 1 week
  only:
    - master

docker-build:
  stage: docker
  image: docker:24.0.5
  services:
    - docker:24.0.5-dind
  variables:
    DOCKER_HOST: tcp://docker:2375
    DOCKER_TLS_CERTDIR: ""
  script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
    - docker buildx build --load -t $DOCKER_IMAGE .
    - docker push $DOCKER_IMAGE
  only:
    - master