{{- if .Values.mysql.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "sdsb.mysql.fullname" . }}
  labels:
    {{- include "sdsb.labels" . | nindent 4 }}
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: {{ required "mysql.rootPassword is required" .Values.mysql.rootPassword | quote }}
  MYSQL_DATABASE: {{ .Values.app.db.database | quote }}
  MYSQL_USER: {{ .Values.app.db.username | quote }}
  MYSQL_PASSWORD: {{ .Values.app.db.password | quote }}
{{- end }}
