apiVersion: v1
kind: Secret
metadata:
  name: {{ include "sdsb.fullname" . }}
  labels:
    {{- include "sdsb.labels" . | nindent 4 }}
type: Opaque
stringData:
  SDSB_USERNAME: {{ .Values.app.db.username | quote }}
  SDSB_PASSWORD: {{ required "app.db.password is required" .Values.app.db.password | quote }}
  BOT_TOKEN: {{ required "app.bot.token is required" .Values.app.bot.token | quote }}
  BOT_NAME: {{ required "app.bot.name is required" .Values.app.bot.name | quote }}
