{{- if .Values.service.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "sdsb.fullname" . }}
  labels:
    {{- include "sdsb.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "sdsb.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: bot
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: http
{{- end }}
